### ISSUE TITLE
[vue-router] Route with name 'Unauthorized' does not exist

### ISSUE THREAD

**Issue by ferreira-guilherme** [rbanks54/vue-and-identityserver#1]
Im getting this error "[vue-router] Route with name 'Unauthorized' does not exist" What i'm doing wrong?

**Comment by rbanks54** [comment]
Oops. I didn't include a route for /unauthorised in the sample code. I'll fix that.

In the meantime, you can just add a new route for it to the router.js file.

**Comment by rbanks54** [comment]
I just added the unauthorized route (79ae5bc5f94038382c7ab2c946eaf25ff3cfb4b4) . If you cancel out of the sign in process, you should get a message indicating the login failed.
