### ISSUE TITLE
replacing global data and global method with VueX

### ISSUE THREAD

**Issue by aakashbashyal21** [rbanks54/vue-and-identityserver#3]
Hey!

I have been already using the vuejs integration with Identity Server 4. I was using `vuex` to persist the the token and user details. But, i found you using gobal data and global method. 

Is there any specific reason for using that? Won't it be better using the store?

And can you extend your implementation with the roles and user permission?

Finally! Thanks for your wonderful post!

**Comment by rbanks54** [comment]
Thanks for the feedback 🙂

I didn't want to include Vuex as a dependency as I didn't want to assume everyone knows or uses it, and using it wouldn't help improve understanding of the concepts discussed in the blog posts.

For roles and user permissions, they should be application specific. I link authenticated users to their roles and permissions within my applications by looking at the email claim and referencing a permissions/roles table within the application. Change to permissions and roles can be made within the application without needing to change identity server's configuration in any way.

Identity Server is responsible for Authentication. Applications are responsible for Authorization. I could add something in the post series about this, but I don't think there's enough value to do so at the moment.  Maybe it should be the subject of a different post in the future?
