### ISSUE TITLE
Q: Using IS4 Register/Login View vs. Vue's Custom Register/Login Page

### ISSUE THREAD

**Issue by BenHayat** [rbanks54/vue-and-identityserver#5]
Hi Richard;

I truly enjoyed (and learned a lot) from your 9 series on "Securing a Vue.js app and API with IdentityServer".
I have two questions if you don't mind answering:

**Q1:** For user's management (Register, Login, Rest password and etc.), is it possible that we can create custom Vue page for user to use our Vue page to enter their credentials and then the SPA calls the back end using Axios to send the credentials to IS4 server, as opposed to the style you chose to redirect a SPA app to IS4 using MVC View page?

If the answer is yes, then which way is safer to use to allow user to enter credentials against hackers?
For example, Firebase offers a UI JS library to allow developers to drop in Vue page and connect directly to backend without redirect. But Azure B2C requires the redirect.

**Q2:** When you created the Vue project, you set it up in such a way to be hosted by IS4 server rather independently hosting the SPA. What is the standard way of doing this if the SPA is going to use .Net API and IS4, and if it should be hosted within IS4 project, why is that?

Thank you in advance for your great series and if you can answer my questions.
..Ben

**Comment by rbanks54** [comment]
I'll answer in reverse order... 😄 

**A2:** The Vue SPA client is served by the Web API project, not Identity Server. This was done purely to limit complexity in the sample.
To serve the Vue client independently of the Web API you would need to add some CORS configuration to the Web API project, and I felt that doing so would be distracting from the main focus of the series - which is authenticating against Identity Server.

**A1:** If you want to build your own front end, you'll need to provide your own APIs for your Vue code to call. It's some work, but it's not hard to do as IdentityServer is just a standard ASP.NET application and you can extend it as you like. I don't recommend it, but if you take this approach, **_please_** take extra care. Think about CORS and all the other security concerns you should consider when deploying unauthenticated endpoints to the big bad internet. Ensure you use tools like web application firewalls and API management services to limit your exposure as having endpoints for identity management exposed to untrusted clients increases your risk profile and may allow people to abuse your identity solution and create accounts with more permissions than you planned.

That said, if you wanted to create a user, for example, you'd need to expose a new API endpoint that did something like the following psuedo code.

```
UserManager<ApplicationUser> userMgr; //populate this via dependency injection

var user = await userMgr.FindByNameAsync("XYZ");
if (user == null)
{
    user = new ApplicationUser
    {
        UserName = "XYZ"
    };
    var result = await userMgr.CreateAsync(user, "...pwd...");
    if (!result.Succeeded)
    {
        throw new MakeUpYourOwnException();
    }

    result = await userMgr.AddClaimsAsync(user, new Claim[]{
        new Claim(JwtClaimTypes.Name, "Slim Shady"),
        //... etc.
    });
    if (!result.Succeeded)
    {
        throw new AnotherException(result.Errors.First().Description);
    }
```

I hope that helps
